name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: omanrai
          outputs: dist
      - name: Upload Snake.svg
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist/github-contribution-grid-snake.svg
